# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16IbsU9u2OMchQBVEgliAsV5RcWuObiKB
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.train(
    data="/content/drive/MyDrive/Colab Notebooks/dataset.yaml",
    epochs=100,
    imgsz=640,
    batch=8,
    augment=True,
    device=0,
)

!scp -r /content/runs '/content/drive/MyDrive/Colab Notebooks'

from ultralytics import YOLO
import os

model = YOLO("/content/drive/MyDrive/Colab Notebooks/runs/detect/train/weights/best.pt")  # Your model

video_folder = "/content/drive/MyDrive/Colab Notebooks/Videos/unknown"  # or your Drive path

for filename in os.listdir(video_folder):
    if filename.endswith(".mp4") or filename.endswith(".avi"):
        video_path = os.path.join(video_folder, filename)
        print(f"Processing {filename}...")
        model.predict(source=video_path, save=True, conf=0.4)

from google.colab import files
import shutil
shutil.make_archive("predicted_videos", 'zip', "runs/detect/predict")
files.download("predicted_videos.zip")

!pip install ultralytics opencv-python numpy deep-sort-realtime

from ultralytics import YOLO
import cv2
import numpy as np
from deep_sort_realtime.deepsort_tracker import DeepSort
from google.colab.patches import cv2_imshow
from google.colab import files

# Initialize YOLOv8 and DeepSORT
model = YOLO("/content/drive/MyDrive/Colab Notebooks/runs/detect/train/weights/best.pt")
tracker = DeepSort(max_age=10, n_init=3, max_cosine_distance=0.4)

# Video settings
VIDEO_PATH = "/content/drive/MyDrive/Colab Notebooks/Videos/test_clips/onside_1 .mp4"
PASS_MOMENT_FRAME = 43  # Frame where pass starts
GOAL_SIDE = "right"     # "left" or "right"

# Open video
cap = cv2.VideoCapture(VIDEO_PATH)
if not cap.isOpened():
    raise ValueError("Couldn't open video file")

# Get video dimensions
ret, frame = cap.read()
if not ret:
    raise ValueError("Failed to read first frame")
height, width = frame.shape[:2]
cap.set(cv2.CAP_PROP_POS_FRAMES, 0)

# Initialize video writer
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter('output.mp4', fourcc, 30, (width, height))

# Persistent visualization data
persistent_offside_line = None
persistent_status = ""

def calculate_center_x(bbox):
    """Calculate horizontal center of bounding box (integer pixel position)"""
    return int((bbox[0] + bbox[2]) / 2)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    current_frame = int(cap.get(cv2.CAP_PROP_POS_FRAMES))

    # YOLOv8 Detection
    results = model.predict(frame, conf=0.5)
    boxes = results[0].boxes.xyxy.cpu().numpy()
    confidences = results[0].boxes.conf.cpu().numpy()
    class_ids = results[0].boxes.cls.cpu().numpy().astype(int)

    # Prepare DeepSORT detections
    detections = []
    for box, conf, cls_id in zip(boxes, confidences, class_ids):
        x1, y1, x2, y2 = box
        detections.append(([x1, y1, x2-x1, y2-y1], conf, cls_id))

    # Update tracker
    tracks = tracker.update_tracks(detections, frame=frame)

    # Process tracks
    players = []
    for track in tracks:
        if not track.is_confirmed():
            continue

        track_id = track.track_id
        ltrb = track.to_ltrb()  # [x1, y1, x2, y2]
        class_id = track.det_class

        players.append({
            "id": track_id,
            "position": ltrb,
            "class": class_id  # 0=attacker, 1=defender, 2=goalkeeper
        })

# ... (keep all previous code until the offside logic section)

    # Offside Logic (Calculate once at pass moment)
    if current_frame == PASS_MOMENT_FRAME:
        attackers = [p for p in players if p["class"] == 0]
        defenders = [p for p in players if p["class"] == 1]
        goalkeepers = [p for p in players if p["class"] == 2]

        # Initialize values
        goalkeeper_bbox = goalkeepers[0]["position"] if goalkeepers else None
        persistent_offside_line = width // 2  # Default to halfway line

        # Defender-based logic
        if len(defenders) > 0:
            if goalkeeper_bbox is not None:  # Defender-goalkeeper proximity
                gk_center = calculate_center_x(goalkeeper_bbox)
                # Convert to NumPy array for vector operations
                defender_centers = np.array([calculate_center_x(d["position"]) for d in defenders])
                distances = np.abs(defender_centers - gk_center)
                closest_defender = defenders[np.argmin(distances)]
            else:  # Goal-side fallback
                defender_centers = np.array([calculate_center_x(d["position"]) for d in defenders])
                if GOAL_SIDE == "right":
                    closest_defender = defenders[np.argmax(defender_centers)]
                else:
                    closest_defender = defenders[np.argmin(defender_centers)]

            persistent_offside_line = calculate_center_x(closest_defender["position"])

        # ... (rest of the code remains the same)

        # Offside check
        offside_players = []
        for attacker in attackers:
            attacker_center = calculate_center_x(attacker["position"])
            if (GOAL_SIDE == "right" and attacker_center > persistent_offside_line) or \
               (GOAL_SIDE == "left" and attacker_center < persistent_offside_line):
                offside_players.append(attacker)

        persistent_status = "OFFSIDE" if offside_players else "ONSIDE"

    # Visualization (All frames after pass moment)
    if current_frame >= PASS_MOMENT_FRAME and persistent_offside_line is not None:
        # Vertical offside line
        cv2.line(frame,
                 (persistent_offside_line, 0),
                 (persistent_offside_line, height),
                 (0, 0, 255), 2)  # Red line

        # Status text
        cv2.putText(frame, persistent_status, (50, 50),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 2)

    # Draw player boxes
    for player in players:
        x1, y1, x2, y2 = player["position"]
        color = (0, 255, 0) if player["class"] == 0 else (255, 0, 0)
        if player["class"] == 2:
            color = (0, 255, 255)  # Yellow for goalkeeper
        cv2.rectangle(frame, (int(x1), int(y1)), (int(x2), int(y2)), color, 2)

    # Write frame to output video
    out.write(frame)

cap.release()
out.release()
files.download('output.mp4')